# Generated by Django 4.1 on 2022-08-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delights_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('g', 'grams'), ('kg', 'kilograms'), ('eggs', 'eggs')], default='g', max_length=4),
        ),
    ]
