# Generated by Django 4.1 on 2022-08-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delights_app', '0002_alter_ingredient_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
    ]
