# Generated by Django 4.1 on 2022-08-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delights_app', '0003_remove_menuitem_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperequirements',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='reciperequirements',
            name='ingredient',
            field=models.ManyToManyField(to='delights_app.ingredient'),
        ),
    ]
